### ISSUE TITLE
Push docker image to docker hub

### ISSUE THREAD

**Issue by petergardfjall** [proofpoint/prom-to-kairosdb#3]
I am interested in trying out this utilty and noticed that a Docker hub repository exists for the project (https://hub.docker.com/r/proofpoint/prom-to-kairosdb/). _However_, the repo is missing images. I would love to see a docker image pushed to Docker hub.

**Comment by rajatjindal** [comment]
Hi

Thanks for the interest

Let me see if i can push a docker image today

**Comment by petergardfjall** [comment]
That would be great

**Comment by petergardfjall** [comment]
The image still appears to be missing. I would imagine this to be a quick fix, no? (as quick as running `make docker push` perhaps?)

**Comment by rajatjindal** [comment]
Hi Peter

I will work with the team that manages docker hub account,

For security reasons not everyone can push to offical proofpoint account

Apologies for the delay

**Comment by petergardfjall** [comment]
I kind of suspected that there was something more to it.. Thanks @rajatjindal !

**Comment by rajatjindal** [comment]
Sorry for the delay, the docker image should be there now, thanks to @john myers
